<a href="https://colab.research.google.com/github/peramdurgashankar18/Ml-Assignments/blob/main/Assignment-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment-1

In [3]:
import numpy as np

1.Perform arithmetic operations on NumPy arrays

In [4]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)


[ 7  9 11 13 15]


2.Write a script to compute the mean and standard deviation of a NumPy array

In [5]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 3.0
Standard Deviation: 1.4142135623730951


3.Create a NumPy array of integers from 10 to 50 with a step size of 5

In [13]:
array = np.arange(10, 50, 5)
print(array)

[10 15 20 25 30 35 40 45]


4.Reshape the array into a 2x4 matrix

In [14]:
reshaped_array = array.reshape(2, 4)
print(reshaped_array)

[[10 15 20 25]
 [30 35 40 45]]


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.


In [18]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = array[1:, :2]
print(sub_matrix)
array[array > 4] = 0
print(array)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements

In [22]:
random_array = np.random.rand(4, 4)
mean_of_columns = np.mean(random_array, axis=0)
max_value = np.max(random_array)
sum_of_elements = np.sum(random_array)
print(mean_of_columns)
print(max_value)
print(sum_of_elements)

[0.51431119 0.76468682 0.52110719 0.36184036]
0.9988371928803943
8.647782222329859


8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [23]:
arr = np.array([1, 2, 3, 4])
result = (arr + 10) * 2
print(result)

[22 24 26 28]


9.. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1

In [27]:
arr = np.random.randint(1, 101, size=(3, 4, 5))
second_layer = arr[1]
print(second_layer)
first_two_rows_last_three_columns = arr[:, :2, -3:]
print(first_two_rows_last_three_columns)
arr[arr % 3 == 0] = -1
print(arr)


[[ 69  10  25  27  45]
 [ 97  39  31  72  32]
 [ 58  17  56  39  29]
 [ 30  97  99 100  50]]
[[[39 83 21]
  [ 8 42 83]]

 [[25 27 45]
  [31 72 32]]

 [[24 27 47]
  [80 77 54]]]
[[[ -1  67  -1  83  -1]
  [ -1  70   8  -1  83]
  [ 53  91  38  40  25]
  [ 98   2  -1  -1  -1]]

 [[ -1  10  25  -1  -1]
  [ 97  -1  31  -1  32]
  [ 58  17  56  -1  29]
  [ -1  97  -1 100  50]]

 [[ 76  13  -1  -1  47]
  [ -1  25  80  77  -1]
  [ -1  -1  -1  97  -1]
  [  2  97  98   4  82]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array

In [32]:
arr = np.random.randint(1, 21, size=(3, 3))
row_means = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_means
print(normalized_arr)
squared_arr = np.square(arr)
print(squared_arr)
flattened_arr = arr.flatten()
sorted_indices = np.argsort(flattened_arr)[::-1]
top_3_indices = sorted_indices[:3]
print(top_3_indices)

[[ 0.33333333  0.33333333 -0.66666667]
 [-6.33333333  4.66666667  1.66666667]
 [ 5.33333333 -3.66666667 -1.66666667]]
[[256 256 225]
 [ 36 289 196]
 [289  64 100]]
[6 4 1]
